fos_rest:
    param_fetcher_listener:
        enabled: true
    format_listener:
        rules :
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
    body_listener:
        enabled: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        view_response_listener: true
        formats:
            json: true
    serializer:
